name: Release Workflow

on:
    push:
      branches:
        - master

jobs:
  build:
    name: CI Pipeline PRD

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install and npm run build
      run: |
        npm ci
        npm run build

    - name: Deploy via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USER}}
        password: ${{secrets.SSH_PASSWORD}}
        port: 990
        overwrite: true
        source: "Ci-Cd-Demo/index.html,favicon.ico,*.js"